STYLE_RULES = [
    "professional fantasy coloring-book line art",
    "pure black ink on a clean white background",
    "portrait page composition",
    "one unmistakable creature or creature group as the first-read focal subject at canonical scale and proportions; use framing rather than enlarging the body",
    "bold clean outer contour",
    "lighter simpler interior lines",
    "large uninterrupted white regions that are enjoyable to color",
    "medium-low detail density",
    "colorability governs the page; the environment must be specific, readable, purposeful, enjoyable to color, and visually secondary to the monster",
    "use two to four large habitat-defining environmental cues arranged around, behind, or beneath the monster instead of competing with it",
    "at least one environmental feature directly supports or interacts with the story moment",
    "no grayscale wash",
    "no painterly shading",
    "almost no crosshatching",
    "minimal solid-black shadow masses",
    "no text, caption, logo, watermark, decorative border, rectangular artwork frame, or inset page box",
    "mature fantasy look; not preschool-cute and not stick-figure simple",
]
