STYLE_RULES = [
    "professional fantasy coloring-book line art",
    "pure black ink on a clean white background",
    "portrait page composition",
    "one large centered unmistakable monster as the dominant focal subject inside an intentional readable environment",
    "bold clean outer contour",
    "lighter simpler interior lines",
    "large uninterrupted white regions that are enjoyable to color",
    "medium-low detail density",
    "environment is a co-equal storytelling pillar but visually secondary to the monster: specific, readable, purposeful, and enjoyable to color",
    "use two to four large habitat-defining environmental cues arranged around, behind, or beneath the monster instead of competing with it",
    "at least one environmental feature directly supports or interacts with the story moment",
    "no grayscale wash",
    "no painterly shading",
    "almost no crosshatching",
    "minimal solid-black shadow masses",
    "no text, caption, logo, watermark, or decorative border",
    "mature fantasy look; not preschool-cute and not stick-figure simple",
]
