STYLE_RULES = [
    "professional fantasy coloring-book line art",
    "pure black ink on a clean white background",
    "portrait page composition",
    "monster, environment, and story moment all read clearly",
    "environment is a co-equal storytelling subject, never generic filler",
    "bold clean outer contours on major forms",
    "lighter simpler interior lines",
    "large uninterrupted white regions that are enjoyable to color",
    "medium-low detail density",
    "two to four strong habitat-defining environmental anchors",
    "clear spatial depth without decorative clutter",
    "no grayscale wash",
    "no painterly shading",
    "almost no crosshatching",
    "minimal solid-black shadow masses",
    "no text, caption, logo, watermark, or decorative border",
    "mature fantasy look; not preschool-cute and not stick-figure simple",
]
