const qs=s=>document.querySelector(s);const selectedTags=new Set();
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const p=await r.json();if(!r.ok)throw new Error(p.error||`HTTP ${r.status}`);return p}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function list(items){return `<ul>${(items||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`}
function render(d){const p=d.current_page,s=d.current_state,c=s.current_candidate;qs("#progress").innerHTML=`<div><strong>${d.progress.approved}/${d.progress.total}</strong></div><div>pages approved</div>`;qs("#pageHeader").innerHTML=`<div><p class="eyebrow">${esc(p.page_id)} · Page ${p.order} of ${d.progress.total}</p><h2>${esc(p.monster_name)}</h2><p class="tagline">${esc(p.habitat)}</p></div><span class="badge">${esc(s.status.replaceAll("_"," "))}</span>`;
if(c?.image_path)qs("#artFrame").innerHTML=`<img src="${esc(c.image_path)}?v=${encodeURIComponent(c.created_at||"")}" alt="Current ${esc(p.monster_name)} candidate">`;else qs("#artFrame").innerHTML=`<div class="placeholder"><div><strong>${esc(p.page_id)} · ${esc(p.monster_name)}</strong><br><br>No generated candidate yet.<br>The page stays here until the local art worker produces one.</div></div>`;
qs("#brief").innerHTML=`<h3>Moment</h3><p>${esc(p.moment)}</p><h3>Identity</h3>${list(p.identity_rules)}<h3>Must Include</h3>${list(p.must_include)}<h3>Must Avoid</h3>${list(p.must_avoid)}${p.modify?`<h3>Current Modify Direction</h3><p><strong>Preserve:</strong></p>${list(p.modify.preserve)}<p><strong>Change:</strong></p>${list(p.modify.change)}<p><strong>Avoid:</strong></p>${list(p.modify.avoid)}`:""}`;
qs("#queue").innerHTML=d.ordered_pages.map(x=>`<div class="queue-row ${x.page_id===d.current_page_id?"current":""} ${x.status==="locked"?"locked":""}"><span>${esc(x.page_id)}</span><span>${esc(x.monster_name)}</span><span class="state">${esc(x.status)}</span></div>`).join("");
qs("#approve").disabled=!(c&&s.status==="awaiting_human");qs("#modify").disabled=!c;qs("#statusLine").innerHTML=c?`Attempt <strong>${c.attempt}</strong> · QA: <strong>${esc(c.qa_status)}</strong> · Supervisor: <strong>${esc(c.supervisor_status)}</strong>`:"<strong>No active candidate.</strong> Waiting for the art worker."}
async function refresh(){try{render(await api("/api/state"))}catch(e){qs("#statusLine").innerHTML=`<span class="error">${esc(e.message)}</span>`}}
async function decide(decision){try{const d=await api("/api/decision",{method:"POST",body:JSON.stringify({decision,notes:qs("#notes").value,quick_tags:[...selectedTags]})});qs("#notes").value="";selectedTags.clear();document.querySelectorAll("[data-tag]").forEach(b=>b.classList.remove("selected"));render(d)}catch(e){qs("#statusLine").innerHTML=`<span class="error">${esc(e.message)}</span>`}}
document.querySelectorAll("[data-tag]").forEach(b=>b.addEventListener("click",()=>{const t=b.dataset.tag;if(selectedTags.has(t)){selectedTags.delete(t);b.classList.remove("selected")}else{selectedTags.add(t);b.classList.add("selected")}}));qs("#approve").addEventListener("click",()=>decide("approve"));qs("#modify").addEventListener("click",()=>decide("modify"));qs("#regenerate").addEventListener("click",()=>decide("regenerate"));refresh();
