const qs=s=>document.querySelector(s);const selectedTags=new Set();
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const p=await r.json();if(!r.ok)throw new Error(p.error||`HTTP ${r.status}`);return p}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function list(items){return `<ul>${(items||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`}
function render(d){const p=d.current_page,s=d.current_state,c=s.current_candidate,m=d.current_monster_spec;qs("#progress").innerHTML=`<div><strong>${d.progress.approved}/${d.progress.total}</strong></div><div>pages approved</div><div id="comfyStatus" class="comfy-status">Checking local artist…</div>`;qs("#pageHeader").innerHTML=`<div><p class="eyebrow">${esc(p.page_id)} · Page ${p.order} of ${d.progress.total}</p><h2>${esc(p.monster_name)}</h2><p class="tagline">${esc(p.habitat)}</p></div><span class="badge">${esc(s.status.replaceAll("_"," "))}</span>`;
if(c?.image_path)qs("#artFrame").innerHTML=`<img src="${esc(c.image_path)}?v=${encodeURIComponent(c.created_at||"")}" alt="Current ${esc(p.monster_name)} candidate">`;else qs("#artFrame").innerHTML=`<div class="placeholder"><div><strong>${esc(p.page_id)} · ${esc(p.monster_name)}</strong><br><br>No generated candidate yet.<br>The page stays here until the local art worker produces one.</div></div>`;
const visual=m?.visual_identity||{},ref=m?.reference||{},refImg=ref.resolved_image;
qs("#referencePanel").innerHTML=m?`<div class="reference-head"><div><p class="eyebrow">Canonical Monster Identity</p><h3>${esc(m.monster_name)}</h3></div><span class="identity-badge">${esc(m.family||"monster")}</span></div>${refImg?`<img class="reference-image" src="${esc(refImg)}" alt="Identity reference for ${esc(m.monster_name)}">`:`<div class="reference-placeholder"><strong>Identity brief active</strong><span>No reference image loaded yet. Anatomy rules still drive generation.</span></div>`}<p class="identity-core">${esc(visual.core_identity||"")}</p><dl class="identity-facts"><dt>Silhouette</dt><dd>${esc(visual.silhouette||"")}</dd><dt>Head</dt><dd>${esc(visual.head_features||"")}</dd><dt>Body</dt><dd>${esc(visual.body_shape||"")}</dd></dl><h4>Monster Accuracy Check</h4>${list(m.accuracy_checks)}<p class="reference-rule">${esc(ref.notes||"Reference art controls anatomy and identity only; Black-Ink controls style.")}</p>`:`<div class="reference-placeholder"><strong>No canonical spec yet</strong><span>This page still uses its page-level identity rules.</span></div>`;
qs("#brief").innerHTML=`<h3>Moment</h3><p>${esc(p.moment)}</p><h3>Identity</h3>${list(p.identity_rules)}<h3>Must Include</h3>${list(p.must_include)}<h3>Must Avoid</h3>${list(p.must_avoid)}${p.modify?`<h3>Current Modify Direction</h3><p><strong>Preserve:</strong></p>${list(p.modify.preserve)}<p><strong>Change:</strong></p>${list(p.modify.change)}<p><strong>Avoid:</strong></p>${list(p.modify.avoid)}`:""}`;
qs("#queue").innerHTML=d.ordered_pages.map(x=>`<div class="queue-row ${x.page_id===d.current_page_id?"current":""} ${x.status==="locked"?"locked":""}"><span>${esc(x.page_id)}</span><span>${esc(x.monster_name)}</span><span class="state">${esc(x.status)}</span></div>`).join("");
qs("#approve").disabled=!(c&&s.status==="awaiting_human");qs("#modify").disabled=!c;qs("#statusLine").innerHTML=c?`Attempt <strong>${c.attempt}</strong> · QA: <strong>${esc(c.qa_status)}</strong> · Supervisor: <strong>${esc(c.supervisor_status)}</strong>`:"<strong>No active candidate.</strong> Waiting for the art worker."}
async function refresh(){try{render(await api("/api/state"))}catch(e){qs("#statusLine").innerHTML=`<span class="error">${esc(e.message)}</span>`}}
async function decide(decision){try{const d=await api("/api/decision",{method:"POST",body:JSON.stringify({decision,notes:qs("#notes").value,quick_tags:[...selectedTags]})});qs("#notes").value="";selectedTags.clear();document.querySelectorAll("[data-tag]").forEach(b=>b.classList.remove("selected"));render(d)}catch(e){qs("#statusLine").innerHTML=`<span class="error">${esc(e.message)}</span>`}}
document.querySelectorAll("[data-tag]").forEach(b=>b.addEventListener("click",()=>{const t=b.dataset.tag;if(selectedTags.has(t)){selectedTags.delete(t);b.classList.remove("selected")}else{selectedTags.add(t);b.classList.add("selected")}}));qs("#approve").addEventListener("click",()=>decide("approve"));qs("#modify").addEventListener("click",()=>decide("modify"));qs("#regenerate").addEventListener("click",()=>decide("regenerate"));refresh();

async function checkComfy(){const el=qs("#comfyStatus");if(!el)return;try{const d=await api("/api/comfy-health");if(d.connected){const gpu=d.devices?.[0]?.name||"GPU detected";el.className="comfy-status comfy-ok";el.textContent="Local artist connected · "+gpu}else{el.className="comfy-status comfy-off";el.textContent="Local artist offline"}}catch(e){el.className="comfy-status comfy-off";el.textContent="Local artist offline"}}
const originalRefresh=refresh;refresh=async function(){await originalRefresh();await checkComfy()};setInterval(checkComfy,10000);
